---
language: node_js
node_js:
  - "stable"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - mkdir travis-phantomjs
  - curl -L -O https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - export PATH=$PWD/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - "npm config set spin false"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
